import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

const distHtml = join(import.meta.dirname, '..', 'dist', 'index.html');
const outFile = join(import.meta.dirname, '..', '..', 'mcp', 'src', 'dashboard', 'html.ts');

const html = readFileSync(distHtml, 'utf-8');

// Escape backticks and template literal expressions in the HTML
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// Auto-generated by packages/dashboard/scripts/generate-html-export.ts
// Do not edit manually — rebuild with: cd packages/dashboard && pnpm run build

export function getDashboardHtml(): string {
  return \`${escaped}\`;
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, output);

console.log(`Generated ${outFile} (${(html.length / 1024).toFixed(1)} KB)`);
